### ISSUE TITLE
Image builder failed due to no space left on device

### ISSUE THREAD

**Issue by prudhvi66** [aws-deepracer-community/deepracer-on-the-spot#105]
DOTS Image builder failed due to the following error:

**CmdExecution: Stderr: failed to register layer: write /usr/local/lib/python3.8/dist-packages/matplotlib/streamplot.py: no space left on device**

Increasing the volume size to 60 resolved the error. 

`vol_id=$(aws ec2 describe-instances --region $(curl http://169.254.169.254/latest/meta-data/placement/region) --instance-ids $id --query 'Reservations[0].Instances[0].BlockDeviceMappings[0].Ebs.VolumeId' --output text)
                      aws ec2 modify-volume --size 60 --volume-id $vol_id --region $(curl http://169.254.169.254/latest/meta-data/placement/region)`
                      
Please review this.

**Comment by MarkRoss-Eviden** [comment]
No issues when building the central images at this time, DRfC which is an upstream project we use has been slimmed down so that may mean we can now fit into the existing space.
