### ISSUE TITLE
Image builder failed due to EC2 Client Error: 'You can’t publicly share this image'

### ISSUE THREAD

**Issue by prudhvi66** [aws-deepracer-community/deepracer-on-the-spot#106]
Got the below error while building the DOTS image:

**Error:'Not all distribution jobs are completed. 1) EC2 Client Error: 'You can’t publicly share this image because block public access for AMIs is enabled for this account. To publicly share the image, you must call the DisableImageBlockPublicAccess API.' when distributing the image from the source account (ID: 8478885XXXXX) to the destination account (ID: 8478885XXXXX) in Region ap-south-1.'**

As a workaround, I have made adjustments to the YAML script, substituting UserIds in place of Usergroups to ensure private storage of the image ([Reference](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-imagebuilder-distributionconfiguration.html#aws-resource-imagebuilder-distributionconfiguration--examples)). Please review the change.

` Type: 'AWS::ImageBuilder::DistributionConfiguration'
    Properties:
      Name: !Sub 'DistributionConfiguration-${AWS::StackName}'
      Distributions:
        - Region: !ImportValue
            Fn::Sub: ${ResourcesStackName}-Region
          AmiDistributionConfiguration:
            Name: !Join
              - '-'
              - - 'deepracer-ami-dist-config'
                - '{{ imagebuilder:buildDate }}'
            AmiTags:
              Name: DeepRacer
            LaunchPermissionConfiguration:
              UserIds:
                - <AWS_ACCOUNT_NUMBER>`
                

![Error](https://github.com/aws-deepracer-community/deepracer-on-the-spot/assets/32975235/ffb866e9-542d-432b-a85e-e8b6d6650f86)

**Comment by MarkRoss-Eviden** [comment]
This PR will fix this issue, please close this issue once merged @tylerwooten - https://github.com/aws-deepracer-community/deepracer-on-the-spot/pull/107
