### ISSUE TITLE
pull docker images at ec2 start provided by the users on the system.env

### ISSUE THREAD

**Issue by MaikelGit** [aws-deepracer-community/deepracer-on-the-spot#14]
some times the users needs to use docker images that are not already available on the EC2 base image.
Hence, if we add a command to the start_training.sh to attempt doing a docker pull xxxx where xxx is each of the images the user has references on the system.env, we will cover that gap. (we will need to only allow specific characters here like numbers, hiphen and letters from a-z)
This is required for old tracks compatibility for example.

**Comment by MaikelGit** [comment]
if we follow this option we will need to decide if we are going to support the -gl docker images, as these require to perform additional validations on the system.env and run additional configuration commands on the EC2

**Comment by markrossatos** [comment]
I think this works now @MaikelGit?  I'v altered to some dev images to test them our for Lars ok?

**Comment by MarkRoss-Eviden** [comment]
I believe this issue to be resolved, so closing.  Base image builder pulls down latest image of each type, specifying relevant image in system.env pulls down at runtime?  Can be reopened if I'm wrong.
