### ISSUE TITLE
Line graph problem in the Dashboard

### ISSUE THREAD

**Issue by akiva-skolnik** [aws-deepracer-community/deepracer-on-the-spot#144]
The graph is taking into account times without episodes, which cause it to be noisy and hard to interpolate
![image](https://github.com/aws-deepracer-community/deepracer-on-the-spot/assets/57216454/7dec2043-58ee-4d16-b386-35cc8e39bb17)

**Comment by MarkRoss-Eviden** [comment]
This functionality come directly from DeepRacer for Cloud, DOTS simply presents it via the link to the NGINX.  Please raise issue in DeepRacer for Cloud repo, thanks.
