### ISSUE TITLE
Wrong data in the dashboard

### ISSUE THREAD

**Issue by akiva-skolnik** [aws-deepracer-community/deepracer-on-the-spot#145]
I have verified this lap appears in the logs.
It also happened with several other completed episodes.

![image](https://github.com/aws-deepracer-community/deepracer-on-the-spot/assets/57216454/a7e9f317-8b3d-456c-b502-eb23e7a93c66)

**Comment by MarkRoss-Eviden** [comment]
This functionality come directly from DeepRacer for Cloud, DOTS simply presents it via the link to the NGINX.  Please raise issue in DeepRacer for Cloud repo, thanks.
