### ISSUE TITLE
Issue with nigix link were the LIVE KVS camera and other links are not working using  - DOTS

### ISSUE THREAD

**Issue by mcsekrish** [aws-deepracer-community/deepracer-on-the-spot#152]
Hi Mark,

Today I tried running the model using DOTS for the default configuration, it is working fine, were the model is getting imported automatically s3 to console. But if I change the track and model prefix name (just adding only the trackname-modelv1-date-time-as reference to remember) and all other parameters are changed as per my requirements. When the instance is created, the Nigix link for launching LIVE KVS and other links are not working. I request you to fix or how to fix this issue.

Your help is much appreciated.

Suggestion - Please update the changes on certain files/links with version series & date/time. 

Thank you for your time consideration.

**Comment by MarkRoss-Eviden** [comment]
The NGINX links to the videos work fine when i test them.  The NGINX website always provides the links, however whether each video stream works is controlled by the following vars: -
DR_CAMERA_MAIN_ENABLE
DR_CAMERA_SUB_ENABLE
DR_CAMERA_KVS_ENABLE

these must be set to true to work successfully.

You will need to provide a much better description including screenshots and such like if this is an issue for you after you've checked the above.  Please reopen the issue with screenshots, your run.env and system.env.

**Comment by mcsekrish** [comment]
Hi Mark, 

Please find the attached snapshot, after creating the model, were Training Evaluation & Overview, Training Progress, Quintiles, HeatMap almost more than 25-30 mins - not working.

![image](https://github.com/user-attachments/assets/1ffb591f-5961-4733-95f9-0063018e03af)

Training/Evaluation monitoring graphs

[Live Grafana Dashboard](http://IPv4:3000/d/adke0lwv5zwg0e/deepracer-training-template?orgId=1update_to_grafana_urlrefresh=10s)

[Training_and_Evaluation_Overview](http://IPv4:8100/Training_and_Evaluation_Overview.html) - **Error - Training analysis is typically available 20-30 minutes into training. Please refresh in a few minutes.** - Not displaying the graph. It was working fine  earlier to the 2019reinvent track and even 4 days a before it was working fine.

[Training_progress](http://IPv4:8100/Training_progress.html) - **Error as below
no stored variable or alias simulation_agg
no stored variable or alias df
no stored variable or alias track
no stored variable or alias complete_ones
Training Progress Graphs
Logs are not yet available.  It typically takes 25 minutes from the start of training for them to be available.**

[Quintiles](http://IPv4:8100/Quintiles.html) - **Error as below
no stored variable or alias simulation_agg
no stored variable or alias df
no stored variable or alias track
no stored variable or alias complete_ones
Training Progress Graphs
Logs are not yet available.  It typically takes 25 minutes from the start of training for them to be available.**

[Reward Heatmap](http://IPv4:8100/Heatmap.html) - **Error as below -
no stored variable or alias simulation_agg
no stored variable or alias df
no stored variable or alias track
no stored variable or alias complete_ones
Training Heatmap
Logs are not yet available.  It typically takes 25 minutes from the start of training for them to be available.
Waypoint Map
Logs are not yet available.  It typically takes 25 minutes from the start of training for them to be available.**

[Data in tables](http://IPv4:8100/Data_tables.html) - **Error - Training analysis is typically available 20-30 minutes into training. Please refresh in a few minutes.** 

[Path_for_complete_laps](http://IPv4:8100/Path_for_complete_laps.html) - **Error - Training analysis is typically available 20-30 minutes into training. Please refresh in a few minutes.** 

Live Grafana, KVS, Main,Sub Camera, TrainingMetrics,deepracer_checkpoints, Access Jupyter Notebook are working.

[Access Jupyter Notebook](http://IPv4:8888/?token=8be574bc41d695876ccd86e7a7f932b6046c52b794a6d9c2) - Working fine
Could you help me how to fix this, really appreciate it.

**Comment by MarkRoss-Eviden** [comment]
The error you're getting means the Jupyter notebook 'import_from_s3.ipynb' isn't able to retrieve your training from S3.

Suggest you try and check that the training files exist in the location defined in that notebook.
You could also amend: -

except Exception:
  print("Logs are not yet available.  It typically takes 25 minutes from the start of training for them to be available.")

to print out your actual exception error message as that may be more useful to you.

Given it works with the defaults I also suggest you try some different options of model name etc to see what does / doesn't work, you may have used some characters s3 doesn't support for example.
