### ISSUE TITLE
create an updated AMI with the latest Python supported version

### ISSUE THREAD

**Issue by MaikelGit** [aws-deepracer-community/deepracer-on-the-spot#38]
This will allow to add additional features that require Python 3.7+

**Comment by MarkRoss-Eviden** [comment]
Hi @MaikelGit, is it the AMI that needs > Python 3.7 or the Docker images for Robomaker, Sagemaker, RLCoach, Analysis?  If i's the containers then this PR will resolve - https://github.com/aws-deepracer-community/deepracer-on-the-spot/pull/93

**Comment by MarkRoss-Eviden** [comment]
OS update to Ubuntu 20.04 in this PR - https://github.com/aws-deepracer-community/deepracer-on-the-spot/pull/96

This issue is resolved by that PR.
