### ISSUE TITLE
Default AMI from Tyler's central account not available outside of us-east-1

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [aws-deepracer-community/deepracer-on-the-spot#46]
@tylerwooten It'd be great if you could update your Image builder to distribute your image around more supported regions?

I noticed an increase in both spot price and interruptions in us-east-1 as the monthly competition draws towards a close, and for example us-east-2 is currently $0.22/hour for g4dn.2xlarge, whereas us-east-1 is up at $0.28-0.30/hour.

**Comment by tylerwooten** [comment]
great idea @markrossatos . I'll use this issue to track this work

**Comment by MarkRoss-Eviden** [comment]
closing as we have issue #62
