### ISSUE TITLE
Add analysis graphs that are visible during training

### ISSUE THREAD

**Issue by MarkitectRoss** [aws-deepracer-community/deepracer-on-the-spot#51]
Add analysis graphs etc. to solution and publish via nginx so they can be view during training.

**Comment by markrossatos** [comment]
I’m going to have a bash at this so hopefully will have something to share after the weekend or if not I’ll misspend my Easter break.  :-)

**Comment by markrossatos** [comment]
https://github.com/aws-deepracer-community/deepracer-on-the-spot/pull/52 will resolve this issue @tylerwooten
