### ISSUE TITLE
Launching a new EC2 instance. Status Reason: Max spot instance count exceeded. Launching EC2 instance failed.

### ISSUE THREAD

**Issue by werneroscar** [aws-deepracer-community/deepracer-on-the-spot#55]
I was troubleshooting an issue where the ASG never seems to scale from 0 to 1 and the CloudFormation deployment fails. This is what I found.
![SharedScreenshot](https://github.com/aws-deepracer-community/deepracer-on-the-spot/assets/75266179/73bb9796-2dd0-44e6-b778-e5460678c62a)

**Comment by MarkRoss-Eviden** [comment]
Hi @werneroscar, have you requested the appropriate Spot Instance Quota from AWS for the instance type you're using?  If you're using the default g4dn.2xlarge instance you'll need quota in the region to use this.

**Comment by werneroscar** [comment]
Thanks
