### ISSUE TITLE
Spot instance interruption fails when using the default AMI (from Tyler's account in North Virginia) after certain number of hours

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [aws-deepracer-community/deepracer-on-the-spot#56]
Hey @tylerwooten, we have a bug with the spot instance interruption when using the default AMI.  

The code that creates the CloudFormation queries your account for the AMI ID, which is then used by the ASG.  If the spot instance gets interrupted fairly quickly afterwards, then the new instance starts fine, but if the Spot Instance gets interrupted a day or two later the ASG cannot start the next instance as the AMI ID no longer exists.  I assume this is due to a clean up routine in your account that publishes it.  I use my own AMIs and I can have spot interruption days after starting and it restarts fine.

I guess we could fix this in one of four ways: -
1) you keep AMIs in your account for longer (e.g. keep a week's worth?) - small increase in cost but not much I'd think
2) you don't update AMIs daily but do it ad-hoc when new releases or Lar's wrapper are provided or the image pipeline code here is updated (that'd save you money)
2) I write a Lambda function to query your account daily which updates the running ASG template config and handles if people are using an AMI from their own account
3) we add it as a constraint in the readme that training beyond 24 hours requires people to use their own AMIs that aren't getting deleted during the training time

What are you thoughts?

**Comment by tylerwooten** [comment]
Mark and I met and discussed this. In the short term, I will update the image builder to only run every 2 weeks. And use this issue to track.

We also want to allow deploy the AMI into 6 regions:
us-east-1
us-east-2
us-west-1
ap-south-1
eu-central-1
sa-east-1
