### ISSUE TITLE
validation.sh

### ISSUE THREAD

**Issue by JamakaDev** [aws-deepracer-community/deepracer-on-the-spot#59]
Not a big deal but I found typo in valdation.sh line 7:

Typo:
if [ $? -eq 4 ]; then echo "error in hyperparameters.**hson**" && exit 1; fi

Corrected:
if [ $? -eq 4 ]; then echo "error in hyperparameters.**json**" && exit 1; fi

**Comment by JamakaDev** [comment]
sorry if this is not an issue, not sure how to notify the project

**Comment by tylerwooten** [comment]
Thanks for raising @JamakaDev ! This has been fixed
