### ISSUE TITLE
Update image builder to only run when dependencies update

### ISSUE THREAD

**Issue by tylerwooten** [aws-deepracer-community/deepracer-on-the-spot#64]
<img width="927" alt="Screen Shot 2023-07-09 at 9 30 30 PM" src="https://github.com/aws-deepracer-community/deepracer-on-the-spot/assets/26447842/12435449-a4a6-4e7d-90b3-045158bd5d1b">

The image builder has a feature that allows it to trigger a new AMI build only if dependencies update. We could use this to trigger a new pipeline whenever a new sagemaker/robomaker/coach version is released.

**Comment by MarkRoss-Eviden** [comment]
On closer look I don't think this will help us, as the dependencies are build dependencies we create in CloudFormation, not upstream dependencies like DRfC, so the build will oly run if we update and bump cloudformation build versions, and then others deploy the updates in their accounts?

To combat this I've done two things, 1) created a git pull before instances are created to DRfC is always up to date, this has been merged - https://github.com/aws-deepracer-community/deepracer-on-the-spot/pull/99 and 2) moved the build to a more cost effective monthly schedule with auto delete of old AMIs - https://github.com/aws-deepracer-community/deepracer-on-the-spot/pull/100 whcih is awaiting review.

Once these are both merged I think we can close this issue.

**Comment by MarkRoss-Eviden** [comment]
PRs merged, closing
