### ISSUE TITLE
Create a Menu with improved usability to view/modify parameters and Launch Trainings

### ISSUE THREAD

**Issue by leoclavero** [aws-deepracer-community/deepracer-on-the-spot#65]
The idea of this effort is to provide a better user experience to deepracer-on-the-spot while upgrading menu.sh. 
File:
[menu.py.txt](https://github.com/aws-deepracer-community/deepracer-on-the-spot/files/12052593/menu.py.txt)
Place it on /deepracer-on-the-spot

usage: 
python3 menu.py

Benefits

- Provide a usability similiar to the AWS Deepracer Console but in CLI mode
- Hide complexity providing similar steps and configuration assistance
- Reduce "cd" and "vi" commands to edit files
- Avoid human errors
- Add your IP menu option
- Train new model or Continue a previous training menu options

**Comment by leoclavero** [comment]
Menu sample:
![Uploading 20230712_162435.jpg…]()

**Comment by tylerwooten** [comment]
<img width="1432" alt="menu" src="https://github.com/aws-deepracer-community/deepracer-on-the-spot/assets/26447842/d0932522-61e5-4235-a1d9-4e25d9cd39d9">

this is great. Did a slight refactor and merged.
