### ISSUE TITLE
option to have training stop after spot interruption

### ISSUE THREAD

**Issue by tylerwooten** [aws-deepracer-community/deepracer-on-the-spot#74]

**Comment by MarkRoss-Eviden** [comment]
Fixed by the code refactoring - https://github.com/aws-deepracer-community/deepracer-on-the-spot/pull/128/

There's  a new run.env var 'DR_CONTINUE_ON_SPOT_INTERRUPTION' which when set to false ends the training rather than continues it, so this issue will be fixed when that branch is merged.
