### ISSUE TITLE
The lambda function to request quota increase crashed

### ISSUE THREAD

**Issue by cloud-ultra-pro-sam** [aws-deepracer-community/deepracer-on-the-spot#85]
In the file base-resources.yaml

The lambda function to request quota increase crashed:
 "LogicalResourceId": "QuotaInvoke", "NoEcho": false, "Data": {"Data": "You must provide a quota value greater than the current quota value"}}

The current quota is hardcore to 16, where I already have 16 for my spot instance in the region.

Workaround: remove all logic for the quota increase in the YAML file.

**Comment by tylerwooten** [comment]
Resolved by https://github.com/aws-deepracer-community/deepracer-on-the-spot/pull/84
